http_port 3128

auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
auth_param basic realm Proxy
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_access deny all

forwarded_for off
request_header_access Via deny all
request_header_access X-Forwarded-For deny all

dns_nameservers 8.8.8.8 1.1.1.1
